=== GabrielNicolasAvellaneda/OpenXava/OpenXavaTest/components/dtds/component.dtd
<?xml version = "1.0" encoding = "ISO-8859-1"?>

<!ELEMENT component (entity, aggregate*, view*, tab*, entity-mapping, aggregate-mapping*)>
<!ATTLIST component
 name ID #REQUIRED
>

<!ELEMENT entity (ejb?, bean?, implements*, (property|reference|collection)*, method*, finder*, postcreate-calculator*, postload-calculator*, postmodify-calculator*, preremove-calculator*, validator*, remove-validator*)>
<!ATTLIST entity
 label CDATA #IMPLIED
>

<!ELEMENT finder (condition?, order?)>
<!ATTLIST finder
	name CDATA #REQUIRED
	arguments CDATA #REQUIRED
	collection (true|false) "false" 
>

<!ELEMENT aggregate   ((bean|ejb)?, implements*, (property|reference|collection)*, method*, finder*, postcreate-calculator*, postload-calculator*, postmodify-calculator*, preremove-calculator*, validator*, remove-validator*)>
<!ATTLIST aggregate
 name ID #REQUIRED
 label CDATA #IMPLIED
>

<!ELEMENT implements EMPTY>
<!ATTLIST implements
 interface CDATA #REQUIRED
>


<!ELEMENT view (property*, (reference-view|property-view|collection-view)*, members?)>
<!ATTLIST view
  name CDATA #IMPLIED
  label CDATA #IMPLIED
  model CDATA #IMPLIED
  members CDATA "*"
>

<!ELEMENT members (#PCDATA|group|section)*>

<!ELEMENT section (#PCDATA|section|group)*>
<!ATTLIST section
  name CDATA #IMPLIED
  label CDATA #IMPLIED
>

<!ELEMENT group (#PCDATA|group)*>
<!ATTLIST group
  name CDATA #IMPLIED
  label CDATA #IMPLIED
>



<!ELEMENT reference-view (search-action?|descriptions-list?)>
<!ATTLIST reference-view
  reference CDATA #REQUIRED
  view CDATA #IMPLIED
  read-only (true|false) "false"
  frame (true|false) "true"
  create (true|false) "true"
  search (true|false) "true"
>

<!ELEMENT descriptions-list EMPTY>
<!ATTLIST descriptions-list
  description-property CDATA #IMPLIED
  description-properties CDATA #IMPLIED
  depends CDATA #IMPLIED
  condition CDATA #IMPLIED  
  order-by-key (true|false) "false"    
  order CDATA #IMPLIED
  label-format (NORMAL|SMALL|NO_LABEL) "NORMAL"
>

<!ELEMENT property-view (on-change?, action*)>
<!ATTLIST property-view
  property CDATA #REQUIRED
  label CDATA #IMPLIED
  read-only (true|false) "false"
  label-format (NORMAL|SMALL|NO_LABEL) "NORMAL"
>

<!ELEMENT on-change EMPTY>
<!ATTLIST on-change
  class CDATA #REQUIRED
>


<!ELEMENT collection-view  (list-properties?, edit-action?, view-action?, list-action*, detail-action*)>
<!ATTLIST collection-view
  collection CDATA #REQUIRED
  view CDATA #IMPLIED
  read-only (true|false) "false"
  edit-only (true|false) "false"
  create-reference (true|false) "true"
>

<!ELEMENT list-properties (#PCDATA)>

<!ELEMENT search-action (set*)>
<!ATTLIST search-action
  action CDATA #IMPLIED
>

<!ELEMENT edit-action EMPTY>
<!ATTLIST edit-action
  action CDATA #IMPLIED
>

<!ELEMENT view-action EMPTY>
<!ATTLIST view-action
  action CDATA #IMPLIED
>


<!ELEMENT detail-action EMPTY>
<!ATTLIST detail-action
  action CDATA #IMPLIED
>

<!ELEMENT list-action EMPTY>
<!ATTLIST list-action
  action CDATA #IMPLIED
>


<!ELEMENT action EMPTY>
<!ATTLIST action
  action CDATA #IMPLIED
>


<!ELEMENT ejb EMPTY>
<!ATTLIST ejb
 remote CDATA #REQUIRED
 home CDATA #REQUIRED
 primaryKey CDATA #REQUIRED
 jndi CDATA #REQUIRED 
>

<!ELEMENT bean EMPTY>
<!ATTLIST bean
 class CDATA #REQUIRED
>

<!ELEMENT property (valid-values?,(calculator|default-value-calculator)?,validator*)>
<!ATTLIST property
 name CDATA #REQUIRED
 label CDATA #IMPLIED
 stereotype CDATA #IMPLIED
 type CDATA #IMPLIED
 size CDATA #IMPLIED
 required (true|false) "false" 
 key (true|false) "false"
 hidden (true|false) "false"
>

<!ELEMENT reference (default-value-calculator?)>
<!ATTLIST reference
 name CDATA #IMPLIED
 label CDATA #IMPLIED
 model CDATA #IMPLIED
 required (true|false) "false"  
 key (true|false) "false"
 role CDATA #IMPLIED
>

<!ELEMENT collection (reference, ((condition?, order?) | calculator), postremove-calculator*)>
<!ATTLIST collection
 name CDATA #REQUIRED
 label CDATA #IMPLIED
 minimum CDATA #IMPLIED 
>

<!ELEMENT method (calculator)>
<!ATTLIST method
 name CDATA #REQUIRED
 type CDATA "void"
 arguments CDATA #IMPLIED
 exceptions CDATA #IMPLIED 
>

<!ELEMENT validator (set*)>
<!ATTLIST validator
 class CDATA #IMPLIED
 name CDATA #IMPLIED
 only-on-create (true|false) "false"
>

<!ELEMENT remove-validator (set*)>
<!ATTLIST remove-validator
 class CDATA #IMPLIED
 name CDATA #IMPLIED
>


<!ELEMENT calculator (set*)>
<!ATTLIST calculator
 class CDATA #REQUIRED
>

<!ELEMENT default-value-calculator (set*)>
<!ATTLIST default-value-calculator
 class CDATA #REQUIRED
 on-create (true|false) "false"
>

<!ELEMENT postcreate-calculator (set*)>
<!ATTLIST postcreate-calculator
 class CDATA #REQUIRED
>

<!ELEMENT postload-calculator (set*)>
<!ATTLIST postload-calculator
 class CDATA #REQUIRED
>

<!ELEMENT postmodify-calculator (set*)>
<!ATTLIST postmodify-calculator
 class CDATA #REQUIRED
>

<!ELEMENT preremove-calculator (set*)>
<!ATTLIST preremove-calculator
 class CDATA #REQUIRED
>

<!ELEMENT postremove-calculator (set*)>
<!ATTLIST postremove-calculator
 class CDATA #REQUIRED
>

<!ELEMENT set EMPTY>
<!ATTLIST set
 property CDATA #REQUIRED
 from CDATA #IMPLIED
 value CDATA #IMPLIED 
>

<!ELEMENT valid-values (valid-value*)>
<!ELEMENT valid-value EMPTY>
<!ATTLIST valid-value
 value CDATA #REQUIRED
>

<!ELEMENT tab
   (filter?, row-style*, property*, properties?, base-condition?, default-order?)
>
<!ATTLIST tab
 name CDATA #IMPLIED
>

<!ELEMENT row-style EMPTY>
<!ATTLIST row-style
 style CDATA #REQUIRED
 property CDATA #REQUIRED
 value CDATA #REQUIRED
>



<!ELEMENT condition
   (#PCDATA)
>
<!ELEMENT order
   (#PCDATA)
>

<!ELEMENT filter (set*)>
<!ATTLIST filter
 class CDATA #REQUIRED
>

<!ELEMENT properties
   (#PCDATA)
>

<!ELEMENT base-condition
   (#PCDATA)
>
  
<!ELEMENT default-order
   (#PCDATA)
>

<!ELEMENT entity-mapping (property-mapping|reference-mapping|multiple-property-mapping)+>
<!ATTLIST entity-mapping
 table CDATA #REQUIRED
>

<!ELEMENT aggregate-mapping (property-mapping|reference-mapping|multiple-property-mapping)+>
<!ATTLIST aggregate-mapping
 aggregate CDATA #REQUIRED
 table CDATA #REQUIRED
>

<!ELEMENT property-mapping (converter?)>
<!ATTLIST property-mapping
 property CDATA #REQUIRED
 column CDATA #REQUIRED
 cmp-type CDATA #IMPLIED 
>

<!ELEMENT multiple-property-mapping (converter, cmp-field+)>
<!ATTLIST multiple-property-mapping
 property CDATA #REQUIRED
>

<!ELEMENT converter (set*)>
<!ATTLIST converter
 class CDATA #REQUIRED
>

<!ELEMENT cmp-field EMPTY>
<!ATTLIST cmp-field
 converter-property CDATA #REQUIRED
 column CDATA #REQUIRED
 cmp-type CDATA #REQUIRED
>

<!ELEMENT reference-mapping
	(reference-mapping-detail+)
>
<!ATTLIST reference-mapping
 reference CDATA #REQUIRED
>


<!ELEMENT reference-mapping-detail (converter?)>
<!ATTLIST reference-mapping-detail
 column CDATA #REQUIRED
 referenced-model-property CDATA #REQUIRED 
>

=== GabrielNicolasAvellaneda/OpenXava/OpenXavaTest/components/Seller.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE component SYSTEM "dtds/component.dtd">

<component name="Seller">

	<entity>
		<property name="number" type="int" key="true"
			size="3" required="true"/>   
		<property name="name" type="String"
			size="40" required="true"/>
		<reference name="level" model="SellerLevel"/>			
		<collection name="customers">	
			<reference model="Customer" role="seller"/>			
		</collection>
		<reference name="boss" model="Seller"/>
		<finder name="all" arguments="" collection="true">
			<condition>1 = 1</condition>
		</finder>
	</entity>
	
	<view members="number; name"/>
	
	<view name="DecorateName">
		<property-view property="number">
			<on-change class="org.openxava.test.actions.DecorateNameAction"/>
		</property-view>
		<members>number; name</members>
	</view>
	
	<view name="Complete">
		<reference-view reference="level">
			<descriptions-list/>
		</reference-view>
		<property-view property="level.id">
			<on-change class="org.openxava.test.actions.OnChangeVoidAction"/>
		</property-view>
		<collection-view collection="customers" view="Simple">
			<list-properties>number, name, remarks, relationWithSeller, seller.level.description</list-properties>
		</collection-view>		
		<members>number; name; level; customers</members>
	</view>
	
	<tab>
		<filter class="org.openxava.test.filters.NumbersToLettersFilter"/>
	</tab>
	
	<entity-mapping table="XAVATEST@separator@SELLER">
		<property-mapping 
			property="number" column="NUMBER"/>
		<property-mapping
			property="name" column="NAME"/>
		<reference-mapping reference="level">
			<reference-mapping-detail column="LEVEL" referenced-model-property="id"/>
		</reference-mapping>
		<reference-mapping reference="boss">
			<reference-mapping-detail column="BOSS" referenced-model-property="number"/>
		</reference-mapping>		
	</entity-mapping> 
	
</component>

=== GabrielNicolasAvellaneda/OpenXava/trunk/OpenXavaTest/components/Quarter.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE component SYSTEM "dtds/component.dtd">

<component name="Quarter">

	<entity>
		<reference name="year" model="AcademicYear" key="true"/>
		<property name="quarter" type="int" key="true" size="1"/>
		<property name="initDate" type="java.util.Date"/>
		<property name="endDate" type="java.util.Date"/>
		<collection name="subjects">
			<reference model="QuarterSubject"/>
		</collection>		
	</entity>
	
	<aggregate name="QuarterSubject">
		<reference name="quarter" key="true"/>
		<property name="code" size="5" key="true"/>
		<property name="description" size="50" key="true"/>
		<collection nmae="groups">
			<reference model="SubjectGroup"/>	
		</collection>
	</aggregate>

	<view>
		<reference-view reference="year">
			<descriptions-list/>
		</reference-view>		
	</view>
			
</component>

=== GabrielNicolasAvellaneda/OpenXava/trunk/OpenXavaTest/components/Issue.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE component SYSTEM "dtds/component.dtd">

<!-- 
This component is mapping to an unqualified table,
ISSUE, without schema, this is for testing the
default schema behaviour
 -->

<component name="Issue">

	<entity>
		<property name="id" type="String" key="true" 
			size="5" required="true"/>
		<property name="description" type="String" 
			size="40" required="true"/>		
		<collection name="comments">
			<reference model="Comment"/>
		</collection>		  						
	</entity>
	
	<aggregate name="Comment">
		<property name="id" type="Integer" key="true" hidden="true"/>
		<property name="date" type="java.util.Date" required="true">
			<default-value-calculator class="org.openxava.calculators.CurrentDateCalculator"/>
		</property>
		<property name="comment" stereotype="MEMO"/>
	</aggregate>
	
	<entity-mapping table="ISSUE">
		<property-mapping
			property="id" column="ID"/>
		<property-mapping
			property="description" column="DESCRIPTION"/>
	</entity-mapping>
	
	<aggregate-mapping aggregate="Comment" table="COMMENT">
		<reference-mapping reference="issue">
			<reference-mapping-detail column="ISSUE_ID" referenced-model-property="id"/>
		</reference-mapping>
		<property-mapping property="id" column="ID"/>
		<property-mapping property="date" column="DATE"/>
		<property-mapping property="comment" column="COMMENT"/>
	</aggregate-mapping> 
				
</component>

=== GabrielNicolasAvellaneda/OpenXava/trunk/OpenXavaTest/components/City.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE component SYSTEM "dtds/component.dtd">

<component name="City">

	<entity>
		<reference name="state" key="true" required="true"/>
		<property name="code" type="String" key="true" size="5" required="true"/>
		<property name="name" type="String" 
			size="20" required="true"/>
	</entity>
	
	<entity-mapping table="XAVATEST@separator@CITY">
		<reference-mapping reference="state">
			<reference-mapping-detail column="STATE" referenced-model-property="id"/>
		</reference-mapping>
		<property-mapping property="code" column="ID"/>
		<property-mapping property="name" column="NAME"/>
	</entity-mapping> 
				
</component>

=== GabrielNicolasAvellaneda/OpenXava/OpenXavaTest/components/Office.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE component SYSTEM "dtds/component.dtd">

<!-- 
	Example of reference with a member shared with a property.
	For this only have to do that reference-mapping-detail column
	match property-mappingn column.
	-->

<component name="Office">

	<entity>
		<property name="zoneNumber" key="true"
			size="3" required="true" type="int"/>   						
		<property name="number" key="true"
			size="3" required="true" type="int"/>   									
		<property name="name" type="String"
			size="40" required="true"/>
		<reference name="mainWarehouse" model="Warehouse2" required="true"/>	
		<reference name="officeManager" model="Clerk"/>	
		<reference name="defaultCarrier" model="Carrier"/>
	</entity>
	
	<tab>
		<properties>zoneNumber, number, name, mainWarehouse.name, officeManager.name, defaultCarrier.name</properties>
	</tab>
						
	<entity-mapping table="XAVATEST@separator@OFFICE">
		<property-mapping 
			property="zoneNumber" column="ZONE"/>	
		<property-mapping 
			property="number" column="NUMBER"/>				
		<property-mapping
			property="name" column="NAME"/>
		<reference-mapping reference="mainWarehouse">
			<reference-mapping-detail 
					referenced-model-property="zoneNumber" 
					column="ZONE"/>
			<reference-mapping-detail 
					referenced-model-property="number" 
					column="WAREHOUSE_NUMBER"/>			
		</reference-mapping>	
		<reference-mapping reference="officeManager">
			<reference-mapping-detail 
					referenced-model-property="zoneNumber" 
					column="ZONE"/>
			<reference-mapping-detail 
					referenced-model-property="officeNumber" 
					column="NUMBER"/>					
			<reference-mapping-detail 
					referenced-model-property="number" 
					column="MANAGER_NUMBER"/>			
		</reference-mapping>			
		<reference-mapping reference="defaultCarrier">
			<reference-mapping-detail 
					referenced-model-property="number" 
					column="CARRIER_NUMBER"/>			
		</reference-mapping>					
	</entity-mapping> 
	
</component>

=== GabrielNicolasAvellaneda/OpenXava/trunk/OpenXavaTest/filtered-files/Color.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE component SYSTEM "dtds/component.dtd">

<!-- 
Number (the key) can be 0
 -->

<component name="Color">

	<entity>
		<property name="number" type="Integer" key="true" size="5" required="false">
			<default-value-calculator class="org.openxava.calculators.IdentityCalculator" on-create="true"/>
		</property>
		<property name="name" type="String"	size="20" required="true"/>
		<property name="version" type="int" version="true"/>	
		<property name="sample" stereotype="IMAGE_LABEL">	
			<calculator class="org.openxava.test.calculators.ColorSampleCalculator">
				<set property="colorName" from="name"/>
			</calculator>
		</property>
	</entity>
		
	<view name="View1">
		<property name="property1" type="String"/>
		<members>property1</members>
	</view>
	
	<view name="View2">
		<property name="property2" type="String"/>
		<members>property2</members>
	</view>
	
	<view name="View2Sub1">
		<property name="property2Sub1" type="String"/>
		<members>property2Sub1</members>
	</view>
	
	<view name="View2Sub2">
		<property name="property2Sub2" type="String"/>
		<members>property2Sub2</members>
	</view>
	
	<view name="Groups">
		<property name="property1" type="String"/>
		<property name="property2" type="String"/>
		<property name="group">
			<valid-values>
				<valid-value value="GROUP1"/>
				<valid-value value="GROUP2"/>
			</valid-values>
		</property>
		<property-view property="group">
			<on-change class="org.openxava.test.actions.OnChangeGroupInColorAction"/>
		</property-view>
		
		<members>
			group; 
			<group name="group1">property1</group>,
			<group name="group2">property2</group> 
		</members>
	</view>

	<view name="Ordinary">
		<members>number; name; sample</members>
	</view>
	
	<entity-mapping table="XAVATEST.COLOR">
		<property-mapping
			property="number" column="NUMBER"/>
		<property-mapping
			property="name" column="NAME"/>
		<property-mapping
			property="version" column="VERSION"/>					
	</entity-mapping> 
				
</component>

=== GabrielNicolasAvellaneda/OpenXava/OpenXavaTest/components/Shipment.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE component SYSTEM "dtds/component.dtd">

<!--
	Example of valid-values with converter used as key
-->

<component name="Shipment">

	<entity>  
		<property name="type" key="true" required="true">
			<valid-values>
				<valid-value value="internal"/>
				<valid-value value="external"/>
			</valid-values>
		</property>
		<property name="mode" key="true" required="true">
			<valid-values>
				<valid-value value="slow"/>
				<valid-value value="medium"/>
				<valid-value value="fast"/>
			</valid-values>
		</property>		
		<property name="number" type="int" key="true" size="5" required="true"/>
		<property name="description" type="String" size="50" required="true"/>
		<finder name="byMode" arguments="int mode" collection="true">
			<condition>${mode} = {0}</condition>
		</finder>
		<finder name="all" arguments="" collection="true"/>
	</entity>		
	
	<entity-mapping table="XAVATEST@separator@SHIPMENT">
		<property-mapping
			property="type" column="TYPE" cmp-type="String">
			<converter class="org.openxava.converters.ValidValuesLetterConverter">
				<set property="letters" value="IE"/>
			</converter>
		</property-mapping>
		<property-mapping
			property="mode" column="MODE"/>		
		<property-mapping
			property="number" column="NUMBER"/>
		<property-mapping
			property="description" column="DESCRIPTION"/>			
	</entity-mapping>
	
</component>

=== GabrielNicolasAvellaneda/OpenXava/OpenXavaTest/components/SubjectGroup.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE component SYSTEM "dtds/component.dtd">

<component name="SubjectGroup">

	<entity>
		<reference name="quarterSubject" key="true"/>
		<property name="code" type="String" key="true" size="10"/>
		<property name="type" type="String" size="10"/>
	</entity>
	
	<view>
		<reference-view reference="quarterSubject">
			<descriptions-list/>
		</reference-view>		
	</view>
			
</component>
