=== GabrielNicolasAvellaneda/OpenXava/OpenXavaTest/components/dtds/component.dtd
<?xml version = "1.0" encoding = "ISO-8859-1"?>

<!ELEMENT component (entity, aggregate*, view*, tab*, entity-mapping, aggregate-mapping*)>
<!ATTLIST component
 name ID #REQUIRED
>

<!ELEMENT entity (ejb?, bean?, implements*, (property|reference|collection)*, method*, finder*, postcreate-calculator*, postload-calculator*, postmodify-calculator*, preremove-calculator*, validator*, remove-validator*)>
<!ATTLIST entity
 label CDATA #IMPLIED
>

<!ELEMENT finder (condition?, order?)>
<!ATTLIST finder
	name CDATA #REQUIRED
	arguments CDATA #REQUIRED
	collection (true|false) "false" 
>

<!ELEMENT aggregate   ((bean|ejb)?, implements*, (property|reference|collection)*, method*, finder*, postcreate-calculator*, postload-calculator*, postmodify-calculator*, preremove-calculator*, validator*, remove-validator*)>
<!ATTLIST aggregate
 name ID #REQUIRED
 label CDATA #IMPLIED
>

<!ELEMENT implements EMPTY>
<!ATTLIST implements
 interface CDATA #REQUIRED
>


<!ELEMENT view (property*, (reference-view|property-view|collection-view)*, members?)>
<!ATTLIST view
  name CDATA #IMPLIED
  label CDATA #IMPLIED
  model CDATA #IMPLIED
  members CDATA "*"
>

<!ELEMENT members (#PCDATA|group|section)*>

<!ELEMENT section (#PCDATA|section|group)*>
<!ATTLIST section
  name CDATA #IMPLIED
  label CDATA #IMPLIED
>

<!ELEMENT group (#PCDATA|group)*>
<!ATTLIST group
  name CDATA #IMPLIED
  label CDATA #IMPLIED
>



<!ELEMENT reference-view (search-action?|descriptions-list?)>
<!ATTLIST reference-view
  reference CDATA #REQUIRED
  view CDATA #IMPLIED
  read-only (true|false) "false"
  frame (true|false) "true"
  create (true|false) "true"
  search (true|false) "true"
>

<!ELEMENT descriptions-list EMPTY>
<!ATTLIST descriptions-list
  description-property CDATA #IMPLIED
  description-properties CDATA #IMPLIED
  depends CDATA #IMPLIED
  condition CDATA #IMPLIED  
  order-by-key (true|false) "false"    
  order CDATA #IMPLIED
  label-format (NORMAL|SMALL|NO_LABEL) "NORMAL"
>

<!ELEMENT property-view (on-change?, action*)>
<!ATTLIST property-view
  property CDATA #REQUIRED
  label CDATA #IMPLIED
  read-only (true|false) "false"
  label-format (NORMAL|SMALL|NO_LABEL) "NORMAL"
>

<!ELEMENT on-change EMPTY>
<!ATTLIST on-change
  class CDATA #REQUIRED
>


<!ELEMENT collection-view  (list-properties?, edit-action?, view-action?, list-action*, detail-action*)>
<!ATTLIST collection-view
  collection CDATA #REQUIRED
  view CDATA #IMPLIED
  read-only (true|false) "false"
  edit-only (true|false) "false"
  create-reference (true|false) "true"
>

<!ELEMENT list-properties (#PCDATA)>

<!ELEMENT search-action (set*)>
<!ATTLIST search-action
  action CDATA #IMPLIED
>

<!ELEMENT edit-action EMPTY>
<!ATTLIST edit-action
  action CDATA #IMPLIED
>

<!ELEMENT view-action EMPTY>
<!ATTLIST view-action
  action CDATA #IMPLIED
>


<!ELEMENT detail-action EMPTY>
<!ATTLIST detail-action
  action CDATA #IMPLIED
>

<!ELEMENT list-action EMPTY>
<!ATTLIST list-action
  action CDATA #IMPLIED
>


<!ELEMENT action EMPTY>
<!ATTLIST action
  action CDATA #IMPLIED
>


<!ELEMENT ejb EMPTY>
<!ATTLIST ejb
 remote CDATA #REQUIRED
 home CDATA #REQUIRED
 primaryKey CDATA #REQUIRED
 jndi CDATA #REQUIRED 
>

<!ELEMENT bean EMPTY>
<!ATTLIST bean
 class CDATA #REQUIRED
>

<!ELEMENT property (valid-values?,(calculator|default-value-calculator)?,validator*)>
<!ATTLIST property
 name CDATA #REQUIRED
 label CDATA #IMPLIED
 stereotype CDATA #IMPLIED
 type CDATA #IMPLIED
 size CDATA #IMPLIED
 required (true|false) "false" 
 key (true|false) "false"
 hidden (true|false) "false"
>

<!ELEMENT reference (default-value-calculator?)>
<!ATTLIST reference
 name CDATA #IMPLIED
 label CDATA #IMPLIED
 model CDATA #IMPLIED
 required (true|false) "false"  
 key (true|false) "false"
 role CDATA #IMPLIED
>

<!ELEMENT collection (reference, ((condition?, order?) | calculator), postremove-calculator*)>
<!ATTLIST collection
 name CDATA #REQUIRED
 label CDATA #IMPLIED
 minimum CDATA #IMPLIED 
>

<!ELEMENT method (calculator)>
<!ATTLIST method
 name CDATA #REQUIRED
 type CDATA "void"
 arguments CDATA #IMPLIED
 exceptions CDATA #IMPLIED 
>

<!ELEMENT validator (set*)>
<!ATTLIST validator
 class CDATA #IMPLIED
 name CDATA #IMPLIED
 only-on-create (true|false) "false"
>

<!ELEMENT remove-validator (set*)>
<!ATTLIST remove-validator
 class CDATA #IMPLIED
 name CDATA #IMPLIED
>


<!ELEMENT calculator (set*)>
<!ATTLIST calculator
 class CDATA #REQUIRED
>

<!ELEMENT default-value-calculator (set*)>
<!ATTLIST default-value-calculator
 class CDATA #REQUIRED
 on-create (true|false) "false"
>

<!ELEMENT postcreate-calculator (set*)>
<!ATTLIST postcreate-calculator
 class CDATA #REQUIRED
>

<!ELEMENT postload-calculator (set*)>
<!ATTLIST postload-calculator
 class CDATA #REQUIRED
>

<!ELEMENT postmodify-calculator (set*)>
<!ATTLIST postmodify-calculator
 class CDATA #REQUIRED
>

<!ELEMENT preremove-calculator (set*)>
<!ATTLIST preremove-calculator
 class CDATA #REQUIRED
>

<!ELEMENT postremove-calculator (set*)>
<!ATTLIST postremove-calculator
 class CDATA #REQUIRED
>

<!ELEMENT set EMPTY>
<!ATTLIST set
 property CDATA #REQUIRED
 from CDATA #IMPLIED
 value CDATA #IMPLIED 
>

<!ELEMENT valid-values (valid-value*)>
<!ELEMENT valid-value EMPTY>
<!ATTLIST valid-value
 value CDATA #REQUIRED
>

<!ELEMENT tab
   (filter?, row-style*, property*, properties?, base-condition?, default-order?)
>
<!ATTLIST tab
 name CDATA #IMPLIED
>

<!ELEMENT row-style EMPTY>
<!ATTLIST row-style
 style CDATA #REQUIRED
 property CDATA #REQUIRED
 value CDATA #REQUIRED
>



<!ELEMENT condition
   (#PCDATA)
>
<!ELEMENT order
   (#PCDATA)
>

<!ELEMENT filter (set*)>
<!ATTLIST filter
 class CDATA #REQUIRED
>

<!ELEMENT properties
   (#PCDATA)
>

<!ELEMENT base-condition
   (#PCDATA)
>
  
<!ELEMENT default-order
   (#PCDATA)
>

<!ELEMENT entity-mapping (property-mapping|reference-mapping|multiple-property-mapping)+>
<!ATTLIST entity-mapping
 table CDATA #REQUIRED
>

<!ELEMENT aggregate-mapping (property-mapping|reference-mapping|multiple-property-mapping)+>
<!ATTLIST aggregate-mapping
 aggregate CDATA #REQUIRED
 table CDATA #REQUIRED
>

<!ELEMENT property-mapping (converter?)>
<!ATTLIST property-mapping
 property CDATA #REQUIRED
 column CDATA #REQUIRED
 cmp-type CDATA #IMPLIED 
>

<!ELEMENT multiple-property-mapping (converter, cmp-field+)>
<!ATTLIST multiple-property-mapping
 property CDATA #REQUIRED
>

<!ELEMENT converter (set*)>
<!ATTLIST converter
 class CDATA #REQUIRED
>

<!ELEMENT cmp-field EMPTY>
<!ATTLIST cmp-field
 converter-property CDATA #REQUIRED
 column CDATA #REQUIRED
 cmp-type CDATA #REQUIRED
>

<!ELEMENT reference-mapping
	(reference-mapping-detail+)
>
<!ATTLIST reference-mapping
 reference CDATA #REQUIRED
>


<!ELEMENT reference-mapping-detail (converter?)>
<!ATTLIST reference-mapping-detail
 column CDATA #REQUIRED
 referenced-model-property CDATA #REQUIRED 
>

=== GabrielNicolasAvellaneda/OpenXava/OpenXavaTest/web/WEB-INF/classes/Course.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE component SYSTEM "dtds/component.dtd">

<component name="Course">

	<entity>
		<property name="year" type="int" size="4" key="true"/>
		<property name="number" type="int" key="true" size="5" hidden="true">
			<default-value-calculator on-create="true"
				class="org.openxava.test.calculators.CourseNumberCalculator"/>
		</property>
		<property name="description" type="String" required="true"/>
	</entity>
	
	<entity-mapping table="XAVATEST.COURSE">
		<property-mapping property="year" column="YEAR"/>
		<property-mapping property="number" column="NUMBER"/>
		<property-mapping property="description" column="DESCRIPTION"/>
	</entity-mapping>	
	
</component>

=== GabrielNicolasAvellaneda/OpenXava/trunk/OpenXavaTest/components/Vehicle.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE component SYSTEM "dtds/component.dtd">

<component name="Vehicle">

	<entity>
	
		<property name="oid" key="true" hidden="true">
			<default-value-calculator class="org.openxava.calculators.UUIDCalculator"/>
		</property>
		
		<property name="code" type="String" size="5"/>		
		<property name="model" type="String" size="40"/>		
		<property name="make" type="String" size="20"/>
	
	</entity>
	
	<view name="Simple">
		<members>code, model, make</members>
	</view>
										
</component>

=== GabrielNicolasAvellaneda/OpenXava/trunk/OpenXavaTest/components/Warehouse2.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE component SYSTEM "dtds/component.dtd">

<!-- 
	A warehouse version with code generated by OpenXava
	-->

<component name="Warehouse2">

	<entity>
		<property name="zoneNumber" key="true"
			size="3" required="true" type="int"/>   			
		<property name="number" key="true"
			size="3" required="true" type="int"/>   
		<property name="name" type="String"
			size="40" required="true"/>
	</entity>
				
	<entity-mapping table="XAVATEST@separator@WAREHOUSE">
		<property-mapping 
			property="zoneNumber" column="ZONE"/>	
		<property-mapping 
			property="number" column="NUMBER"  cmp-type="Integer">
			<converter class="org.openxava.converters.IntegerNumberConverter"/>						
		</property-mapping>
		<property-mapping
			property="name" column="NAME"/>
	</entity-mapping> 
	
</component>

=== GabrielNicolasAvellaneda/OpenXava/trunk/OpenXavaTest/components/Product3.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE component SYSTEM "dtds/component.dtd">

<!--
Store oid of family and not the code
-->

<component name="Product3">

	<entity>		
		<property name="number" key="true" type="long"
			size="10" required="true"/>    
		<property name="description" type="String"
			size="40" required="true"/>
		<reference name="family" model="Family" required="true"/>
		<property name="comments" stereotype="MEMO"/>
	</entity> 
	
	<view name="WithDescriptionsList">
		<reference-view reference="family">
			<descriptions-list/>
		</reference-view>

		<property-view property="family.oid">
			<on-change class="org.openxava.test.actions.OnChangeFamilyAction"/>
		</property-view>		

		<property-view property="description">
			<on-change class="org.openxava.test.actions.OnChangeProduct3DescriptionAction"/>
		</property-view>						
	</view>
		
	<entity-mapping table="XAVATEST@separator@PRODUCT3">
		<property-mapping 
			property="number" column="NUMBER"/>
		<property-mapping 
			property="description" column="DESCRIPTION"/>
		<reference-mapping reference="family">
			<reference-mapping-detail 
				column="FAMILY" 
				referenced-model-property="oid"/>
		</reference-mapping>	
		<property-mapping 
			property="comments" column="COMMENTS"/>		
	</entity-mapping> 

</component>

=== GabrielNicolasAvellaneda/OpenXava/trunk/OpenXavaTest/components/Customer.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE component SYSTEM "dtds/component.dtd">

<component name="Customer">

	<entity>
		<implements interface="org.openxava.test.ejb.IWithName"/>		
		<property name="number" type="int" key="true"
			size="5" required="true"/>
		<property name="name" stereotype="PERSON_NAME" required="true"/>	
		<property name="type"
			required="true">   
			<valid-values>      
				<valid-value value="normal"/>      
				<valid-value value="steady"/>      
				<valid-value value="special"/>     
			</valid-values>  			
			<default-value-calculator class="org.openxava.calculators.IntegerCalculator">
				<set property="value" value="1"/>
			</default-value-calculator>     
		</property>

		<property name="photo" required="false" stereotype="PHOTO"/>        
		<property name="remarks"
				stereotype="MEMO"
				size="400"/>
		  
		<reference name="address"	model="Address" required="true"/>

		<reference name="seller" model="Seller"/>   

		<reference name="alternateSeller" model="Seller"/>   
						 
		<property name="relationWithSeller"
			type="String" size="40">
			<default-value-calculator class="org.openxava.calculators.StringCalculator">
				<set property="string" value="GOOD"/>
			</default-value-calculator>
		</property>
			
		<collection name="deliveryPlaces">
			<reference model="DeliveryPlace"/>
		</collection>	

		<finder name="byNumber" arguments="int number">
			<condition>${number} = {0}</condition>
		</finder>
		
				
		<finder name="byNameLike" arguments="String name" collection="true">
			<condition>${name} like {0}</condition>
			<order>${name} desc</order>
		</finder>
		
		<finder name="byNameLikeAndrelationWithSeller" arguments="String name, String relationWithSeller" collection="true">
			<condition>${name} like {0} and ${relationWithSeller} = {1}</condition>
			<order>${name} desc</order>
		</finder>
		
		<finder name="normalOnes" arguments="" collection="true">
			<condition>${type} = 1</condition>
		</finder>
						
		<finder name="steadyOnes" arguments="" collection="true">
			<condition>${type} = 2</condition>
		</finder>
		
		<finder name="all" arguments="" collection="true"/>
															
	</entity>

	<aggregate name="Address">		
		<implements interface="org.openxava.test.ejb.IWithCity"/>						
		<property name="street" type="String" size="30" required="true"/> 
		<property name="zipCode" type="int" size="5" required="true"/>  
		<property name="city" type="String" size="20"	required="true"/>  
		<reference name="state" required="true"/>
	</aggregate>	
	
	<aggregate name="DeliveryPlace">		
		<property name="oid" type="String" key="true" hidden="true">
			<default-value-calculator 
				class="org.openxava.calculators.UUIDCalculator"
				on-create="true"/>
		</property>		
		<property name="name" type="String" 
			size="30" required="true"/> 
		<property name="address" type="String"			
			size="50" required="true"/>  			
		<reference name="preferredWarehouse" model="Warehouse2"/>
		<property name="remarks" type="String" size="40"/>
			
		<collection name="receptionists">
			<reference model="Receptionist"/>			
		</collection>	
	</aggregate>	

	<aggregate name="Receptionist">
		<property name="oid" type="int" key="true" hidden="true">
			<default-value-calculator 
				class="org.openxava.calculators.NextIntegerCalculator"
				on-create="true">
				<set property="model" value="Customer.Receptionist"/>
				<set property="property" value="oid"/>
			</default-value-calculator>
		</property>				
		<property name="name" type="String" size="30" required="true"/>
		<finder name="all" arguments="" collection="true"/>
	</aggregate>	

	<view>
		<!-- 
		For overwrite the label better resource files.
		See OpenXavaTest-labels.properties for examples.
		-->
		<property-view property="type" label="Tipet"/>
		
		<property-view property="name">
			<on-change class="org.openxava.test.actions.OnChangeCustomerNameAction"/>
		</property-view>		
		
		<property-view property="alternateSeller.number">
			<on-change class="org.openxava.test.actions.OnChangeVoidAction"/>
		</property-view>
						
		<reference-view reference="seller" frame="false">
			<search-action action="MyReference.search"/>
		</reference-view>			
		
		<reference-view reference="alternateSeller" view="DecorateName" create="false"/>

		<members>
			number; 
			type; 
			name; 
			photo; 
			address; 
			<group name="seller">
				seller;
				relationWithSeller; 
			</group>
			alternateSeller; 
			deliveryPlaces; 
			remarks
		</members>		
						
	</view>
	
	<view name="WithSection">		
		<property-view property="name">
			<on-change class="org.openxava.test.actions.OnChangeCustomerNameAction"/>
		</property-view>		
		
		<property-view property="alternateSeller.number">
			<on-change class="org.openxava.test.actions.OnChangeVoidAction"/>
		</property-view>

		<reference-view reference="seller" frame="false">
			<search-action action="MyReference.search"/>
		</reference-view>			
		
		<reference-view reference="alternateSeller" view="DecorateName"/>

		<members>
			number; 
			<section name="customer">
				type; 
				name; 
				photo; 
				address; 
				<group name="seller">
					seller;
					relationWithSeller; 
				</group>
				alternateSeller; 
				deliveryPlaces; 
				remarks
			</section>
		</members>
				
	</view>
		
	<view name="Simple" members="number; type; name; address"/>
	
	<view name="SomeMembersReadOnly" members="number; type; name; seller; alternateSeller">
		<property-view property="name" read-only="true"/>
		<reference-view reference="seller" read-only="true"/>
		<reference-view reference="alternateSeller" read-only="true">
			<descriptions-list description-properties="level.description, name"/>
		</reference-view>
	</view>

	<view name="SectionGroup">	
		<members>
			number;
			<section name="data">
				<group name="customer">
					type;
					name; 
				</group>
				<group name="seller">
					seller;
					relationWithSeller; 
				</group>
			</section>
		</members>				
	</view>
				
	<view model="Address">
				
		<property name="viewProperty" type="String"/>
		
		 <!-- By default is NORMAL, hence the next line is optional -->
		<property-view property="street" label-format="NORMAL"/>
		<property-view property="zipCode" label-format="SMALL"/>
		<property-view property="city" label-format="NO_LABEL"/>
		<reference-view reference="state">
			<descriptions-list/>
		</reference-view>

		<members>
			viewProperty;
			street, zipCode, city, state;
		</members>
	</view>
	
	<view model="DeliveryPlace">	
		<reference-view reference="preferredWarehouse">
			<descriptions-list/>
		</reference-view>
		<property-view property="preferredWarehouse.number">
			<on-change class="org.openxava.test.actions.OnChangePreferredWarehouseAction"/>
		</property-view>
	</view>
	
	<tab>
		<row-style style="highlight" property="type" value="steady"/>
		<properties>name, type, seller.name, address.city, seller.level.description</properties>	
	</tab>
	
	<tab name="Complete"/>
	
	<tab name="TwoSellers">
		<properties>name, type, seller.number, alternateSeller.number</properties>	
	</tab>
		
	<entity-mapping table="XAVATEST@separator@CUSTOMER">
		<property-mapping
			property="number" column="NUMBER"/>
		<property-mapping
			property="name" column="NAME"/>
		<property-mapping
			property="type" column="TYPE"/>
		<property-mapping
			property="remarks" column="REMARKS"/>			
		<property-mapping
			property="photo" column="PHOTO"/>						
		<reference-mapping reference="seller">
			<reference-mapping-detail
				column="SELLER_NUMBER" 
				referenced-model-property="number"/> 
		</reference-mapping>	
		<reference-mapping reference="alternateSeller">
			<reference-mapping-detail
				column="ALTERNATESELLER_NUMBER" 
				referenced-model-property="number"/> 
		</reference-mapping>			
		<property-mapping
			property="relationWithSeller" column="RELATIONSELLER"/>								
		<property-mapping
			property="address_street" column="STREET"/>						
		<property-mapping
			property="address_zipCode" column="ZIPCODE" cmp-type="String">			
			<converter class="org.openxava.converters.IntegerStringConverter"/>
		</property-mapping>
		<property-mapping
			property="address_city" column="CITY"/>						
		<reference-mapping reference="address_state">						
			<reference-mapping-detail column="STATE" referenced-model-property="id"/>
		</reference-mapping>
	</entity-mapping> 	
	
	<aggregate-mapping aggregate="DeliveryPlace" table="XAVATEST@separator@DELIVERYPLACE">
		<reference-mapping reference="customer">
			<reference-mapping-detail 
				column="CUSTOMER" 
				referenced-model-property="number"/> 
		</reference-mapping>				
		<property-mapping property="oid" column="OID"/>
		<property-mapping property="name" column="NAME"/>
		<property-mapping property="address" column="ADDRESS"/>		
		<property-mapping property="remarks" column="REMARKS"/>
		<reference-mapping reference="preferredWarehouse">
			<reference-mapping-detail 
				column="WAREHOUSE_ZONE" 
				referenced-model-property="zoneNumber"/> 
			<reference-mapping-detail 
				column="WAREHOUSE_NUMBER" 
				referenced-model-property="number"/> 				
		</reference-mapping>						
	</aggregate-mapping>
	
	<aggregate-mapping aggregate="Receptionist" table="XAVATEST@separator@RECEPTIONIST">
		<reference-mapping reference="deliveryPlace">
			<reference-mapping-detail 
				column="DELIVERYPLACE" 
				referenced-model-property="oid"/> 
		</reference-mapping>				
		<property-mapping property="oid" column="OID"/>
		<property-mapping property="name" column="NAME"/>
	</aggregate-mapping>	
						
</component>

=== GabrielNicolasAvellaneda/OpenXava/OpenXavaTest/components/ServiceInvoice.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE component SYSTEM "dtds/component.dtd">

<component name="ServiceInvoice">

	<entity>
		<property name="oid" type="String" key="true" hidden="true">
			<default-value-calculator class="org.openxava.calculators.UUIDCalculator" on-create="true"/>
		</property>
		<property name="year" type="int" search-key="true" size="4">
			<default-value-calculator class="org.openxava.calculators.CurrentYearCalculator"/>	
		</property>		
		<property name="number" type="int" search-key="true" size="6"/>		
		<property name="description" stereotype="MEMO"/>		
		<property name="amount" stereotype="MONEY"/>
	</entity>
	
	
	<view members="year, number, amount; description"/>
	
	<tab >
		<properties>year, number, description, amount+</properties>
	</tab>
	
	<!-- 
	Do not put here a mapping, 
	because this entity is for testing default mapping  
	-->
													
</component>

=== GabrielNicolasAvellaneda/OpenXava/trunk/OpenXavaTest/web/WEB-INF/classes/Task.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE component SYSTEM "dtds/component.dtd">

<component name="Task">

	<entity>
		<property name="oid" type="String" key="true" hidden="true">
			<default-value-calculator class="org.openxava.calculators.UUIDCalculator" 
				on-create="true"/>
		</property>
		<property name="user" stereotype="NO_FORMATING_STRING" size="50" required="true">			  
			<default-value-calculator class="org.openxava.calculators.CurrentUserCalculator"/>				
		</property>
		<property name="date" type="java.util.Date" required="true">
			<default-value-calculator class="org.openxava.calculators.CurrentDateCalculator"/>				
		</property>
		<property name="summary" type="java.lang.String" size="50" required="true"/>
		<property name="comments" stereotype="MEMO"/>
	</entity>
	
	<view>
		<property-view property="user" read-only="true"/>
	</view>
	
	<tab>
		<filter class="org.openxava.filters.UserFilter"/>
		<base-condition>${user} = ?</base-condition>
	</tab>
					
	<entity-mapping table="XAVATEST_TASK">
		<property-mapping property="oid" column="ID"/>
		<property-mapping property="user" column="USERNAME"/>
		<property-mapping property="date" column="DATE"/>
		<property-mapping property="summary" column="SUMMARY"/>
		<property-mapping property="comments" column="COMMENTS"/>
	</entity-mapping> 
				
</component>

=== GabrielNicolasAvellaneda/OpenXava/OpenXavaTest/components/Warehouse.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE component SYSTEM "dtds/component.dtd">

<!-- Implemented with a handmade EJB -->

<component name="Warehouse">

	<!-- 
		Resource files (Labels.properties and ${project}-labels.properties 
		take preference over label attribute, and i18n files is 
		prefered over 'label' attribute'.
		-->
	<entity label="Warehouse">
		<ejb remote="org.openxava.test.ejb.Warehouse"
			home="org.openxava.test.ejb.WarehouseHome"
			primaryKey="org.openxava.test.ejb.WarehouseKey"
			jndi="ejb/openxava.test/Warehouse"/>		
		<!-- 
			We set the types in zone and number because
			code is generate in OTHERS beans with references
			to this. If this is not the case not would be needed.
		-->			
		<property name="zoneNumber" label="Zone"
			size="3" required="true" type="int"/>   			
		<property name="number"
			size="3" required="true" type="int"/>   
		<property name="name"
			size="40" required="true"/>
	</entity>
				
	<entity-mapping table="XAVATEST@separator@WAREHOUSE">
		<property-mapping 
			property="zoneNumber" column="ZONE"/>	
		<property-mapping 
			property="number" column="NUMBER"/>
		<property-mapping
			property="name" column="NAME"/>
	</entity-mapping> 
	
</component>
