=== GabrielNicolasAvellaneda/OpenXava/OpenXavaTest/components/dtds/component.dtd
<?xml version = "1.0" encoding = "ISO-8859-1"?>

<!ELEMENT component (entity, aggregate*, view*, tab*, entity-mapping, aggregate-mapping*)>
<!ATTLIST component
 name ID #REQUIRED
>

<!ELEMENT entity (ejb?, bean?, implements*, (property|reference|collection)*, method*, finder*, postcreate-calculator*, postload-calculator*, postmodify-calculator*, preremove-calculator*, validator*, remove-validator*)>
<!ATTLIST entity
 label CDATA #IMPLIED
>

<!ELEMENT finder (condition?, order?)>
<!ATTLIST finder
	name CDATA #REQUIRED
	arguments CDATA #REQUIRED
	collection (true|false) "false" 
>

<!ELEMENT aggregate   ((bean|ejb)?, implements*, (property|reference|collection)*, method*, finder*, postcreate-calculator*, postload-calculator*, postmodify-calculator*, preremove-calculator*, validator*, remove-validator*)>
<!ATTLIST aggregate
 name ID #REQUIRED
 label CDATA #IMPLIED
>

<!ELEMENT implements EMPTY>
<!ATTLIST implements
 interface CDATA #REQUIRED
>


<!ELEMENT view (property*, (reference-view|property-view|collection-view)*, members?)>
<!ATTLIST view
  name CDATA #IMPLIED
  label CDATA #IMPLIED
  model CDATA #IMPLIED
  members CDATA "*"
>

<!ELEMENT members (#PCDATA|group|section)*>

<!ELEMENT section (#PCDATA|section|group)*>
<!ATTLIST section
  name CDATA #IMPLIED
  label CDATA #IMPLIED
>

<!ELEMENT group (#PCDATA|group)*>
<!ATTLIST group
  name CDATA #IMPLIED
  label CDATA #IMPLIED
>



<!ELEMENT reference-view (search-action?|descriptions-list?)>
<!ATTLIST reference-view
  reference CDATA #REQUIRED
  view CDATA #IMPLIED
  read-only (true|false) "false"
  frame (true|false) "true"
  create (true|false) "true"
  search (true|false) "true"
>

<!ELEMENT descriptions-list EMPTY>
<!ATTLIST descriptions-list
  description-property CDATA #IMPLIED
  description-properties CDATA #IMPLIED
  depends CDATA #IMPLIED
  condition CDATA #IMPLIED  
  order-by-key (true|false) "false"    
  order CDATA #IMPLIED
  label-format (NORMAL|SMALL|NO_LABEL) "NORMAL"
>

<!ELEMENT property-view (on-change?, action*)>
<!ATTLIST property-view
  property CDATA #REQUIRED
  label CDATA #IMPLIED
  read-only (true|false) "false"
  label-format (NORMAL|SMALL|NO_LABEL) "NORMAL"
>

<!ELEMENT on-change EMPTY>
<!ATTLIST on-change
  class CDATA #REQUIRED
>


<!ELEMENT collection-view  (list-properties?, edit-action?, view-action?, list-action*, detail-action*)>
<!ATTLIST collection-view
  collection CDATA #REQUIRED
  view CDATA #IMPLIED
  read-only (true|false) "false"
  edit-only (true|false) "false"
  create-reference (true|false) "true"
>

<!ELEMENT list-properties (#PCDATA)>

<!ELEMENT search-action (set*)>
<!ATTLIST search-action
  action CDATA #IMPLIED
>

<!ELEMENT edit-action EMPTY>
<!ATTLIST edit-action
  action CDATA #IMPLIED
>

<!ELEMENT view-action EMPTY>
<!ATTLIST view-action
  action CDATA #IMPLIED
>


<!ELEMENT detail-action EMPTY>
<!ATTLIST detail-action
  action CDATA #IMPLIED
>

<!ELEMENT list-action EMPTY>
<!ATTLIST list-action
  action CDATA #IMPLIED
>


<!ELEMENT action EMPTY>
<!ATTLIST action
  action CDATA #IMPLIED
>


<!ELEMENT ejb EMPTY>
<!ATTLIST ejb
 remote CDATA #REQUIRED
 home CDATA #REQUIRED
 primaryKey CDATA #REQUIRED
 jndi CDATA #REQUIRED 
>

<!ELEMENT bean EMPTY>
<!ATTLIST bean
 class CDATA #REQUIRED
>

<!ELEMENT property (valid-values?,(calculator|default-value-calculator)?,validator*)>
<!ATTLIST property
 name CDATA #REQUIRED
 label CDATA #IMPLIED
 stereotype CDATA #IMPLIED
 type CDATA #IMPLIED
 size CDATA #IMPLIED
 required (true|false) "false" 
 key (true|false) "false"
 hidden (true|false) "false"
>

<!ELEMENT reference (default-value-calculator?)>
<!ATTLIST reference
 name CDATA #IMPLIED
 label CDATA #IMPLIED
 model CDATA #IMPLIED
 required (true|false) "false"  
 key (true|false) "false"
 role CDATA #IMPLIED
>

<!ELEMENT collection (reference, ((condition?, order?) | calculator), postremove-calculator*)>
<!ATTLIST collection
 name CDATA #REQUIRED
 label CDATA #IMPLIED
 minimum CDATA #IMPLIED 
>

<!ELEMENT method (calculator)>
<!ATTLIST method
 name CDATA #REQUIRED
 type CDATA "void"
 arguments CDATA #IMPLIED
 exceptions CDATA #IMPLIED 
>

<!ELEMENT validator (set*)>
<!ATTLIST validator
 class CDATA #IMPLIED
 name CDATA #IMPLIED
 only-on-create (true|false) "false"
>

<!ELEMENT remove-validator (set*)>
<!ATTLIST remove-validator
 class CDATA #IMPLIED
 name CDATA #IMPLIED
>


<!ELEMENT calculator (set*)>
<!ATTLIST calculator
 class CDATA #REQUIRED
>

<!ELEMENT default-value-calculator (set*)>
<!ATTLIST default-value-calculator
 class CDATA #REQUIRED
 on-create (true|false) "false"
>

<!ELEMENT postcreate-calculator (set*)>
<!ATTLIST postcreate-calculator
 class CDATA #REQUIRED
>

<!ELEMENT postload-calculator (set*)>
<!ATTLIST postload-calculator
 class CDATA #REQUIRED
>

<!ELEMENT postmodify-calculator (set*)>
<!ATTLIST postmodify-calculator
 class CDATA #REQUIRED
>

<!ELEMENT preremove-calculator (set*)>
<!ATTLIST preremove-calculator
 class CDATA #REQUIRED
>

<!ELEMENT postremove-calculator (set*)>
<!ATTLIST postremove-calculator
 class CDATA #REQUIRED
>

<!ELEMENT set EMPTY>
<!ATTLIST set
 property CDATA #REQUIRED
 from CDATA #IMPLIED
 value CDATA #IMPLIED 
>

<!ELEMENT valid-values (valid-value*)>
<!ELEMENT valid-value EMPTY>
<!ATTLIST valid-value
 value CDATA #REQUIRED
>

<!ELEMENT tab
   (filter?, row-style*, property*, properties?, base-condition?, default-order?)
>
<!ATTLIST tab
 name CDATA #IMPLIED
>

<!ELEMENT row-style EMPTY>
<!ATTLIST row-style
 style CDATA #REQUIRED
 property CDATA #REQUIRED
 value CDATA #REQUIRED
>



<!ELEMENT condition
   (#PCDATA)
>
<!ELEMENT order
   (#PCDATA)
>

<!ELEMENT filter (set*)>
<!ATTLIST filter
 class CDATA #REQUIRED
>

<!ELEMENT properties
   (#PCDATA)
>

<!ELEMENT base-condition
   (#PCDATA)
>
  
<!ELEMENT default-order
   (#PCDATA)
>

<!ELEMENT entity-mapping (property-mapping|reference-mapping|multiple-property-mapping)+>
<!ATTLIST entity-mapping
 table CDATA #REQUIRED
>

<!ELEMENT aggregate-mapping (property-mapping|reference-mapping|multiple-property-mapping)+>
<!ATTLIST aggregate-mapping
 aggregate CDATA #REQUIRED
 table CDATA #REQUIRED
>

<!ELEMENT property-mapping (converter?)>
<!ATTLIST property-mapping
 property CDATA #REQUIRED
 column CDATA #REQUIRED
 cmp-type CDATA #IMPLIED 
>

<!ELEMENT multiple-property-mapping (converter, cmp-field+)>
<!ATTLIST multiple-property-mapping
 property CDATA #REQUIRED
>

<!ELEMENT converter (set*)>
<!ATTLIST converter
 class CDATA #REQUIRED
>

<!ELEMENT cmp-field EMPTY>
<!ATTLIST cmp-field
 converter-property CDATA #REQUIRED
 column CDATA #REQUIRED
 cmp-type CDATA #REQUIRED
>

<!ELEMENT reference-mapping
	(reference-mapping-detail+)
>
<!ATTLIST reference-mapping
 reference CDATA #REQUIRED
>


<!ELEMENT reference-mapping-detail (converter?)>
<!ATTLIST reference-mapping-detail
 column CDATA #REQUIRED
 referenced-model-property CDATA #REQUIRED 
>

=== GabrielNicolasAvellaneda/OpenXava/OpenXavaTest/components/Family.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE component SYSTEM "dtds/component.dtd">

<!-- 
	Implemented using a handmade xdoclet EJB 
	Version withou oid exists (Family2)
-->

<component name="Family">

	<entity>
		<ejb remote="org.openxava.test.ejb.Family"
			home="org.openxava.test.ejb.FamilyHome"
			primaryKey="org.openxava.test.ejb.FamilyKey"
			jndi="ejb/openxava.test/Family"/>		
		<property name="oid" type="String" hidden="true" key="true"/>
		<property name="number" size="3" required="true"/>   
		<property name="description" size="40" required="true"/>
	</entity>
	
	<view>
		<property name="products" stereotype="PRODUCT3"/>
		<members>number; description; products</members>
	</view>	
	
	<tab>		
		<default-order>${number} asc</default-order>
	</tab>	
	
	<entity-mapping table="XAVATEST@separator@FAMILY">
		<property-mapping 
			property="oid" column="OID"/>	
		<property-mapping 
			property="number" column="NUMBER"/>
		<property-mapping
			property="description" column="DESCRIPTION"/>
	</entity-mapping> 
	
</component>

=== GabrielNicolasAvellaneda/OpenXava/trunk/OpenXavaTest/filtered-files/Carrier.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE component SYSTEM "dtds/component.dtd">

<component name="Carrier">

	<entity>
		<property name="number" type="int" key="true" 
			size="5" required="true"/>
		<property name="name" stereotype="NO_FORMATING_STRING"
			size="40" required="true"/>			  
		<property name="calculated" type="String"
			size="10">			  			
			<calculator class="org.openxava.calculators.StringCalculator">
				<set property="string" value="TR"/>
			</calculator>
		</property>
		<reference name="drivingLicence"/>
		<reference name="warehouse"
			model="Warehouse" required="true"/>
			
		<!-- Others carriers of same warehouse -->	
		<collection name="fellowCarriers"> 			
			<reference model="Carrier" />			
			<condition>
				${warehouse.zoneNumber} = ${this.warehouse.zoneNumber} AND 
				${warehouse.number} = ${this.warehouse.number} AND 
				NOT (${number} = ${this.number})
			</condition>
		</collection>
		
		<!-- The same that 'fellowCarriers' but implemented with a calculator -->
		<collection name="fellowCarriersCalculated"> 			
			<reference model="Carrier"/>			
			<calculator class="org.openxava.test.calculators.FellowCarriersCalculator"/>
		</collection>		
		
		<property name="remarks" stereotype="MEMO">
			<default-value-calculator class="org.openxava.test.calculators.CarrierRemarksCalculator">
				<set property="drivingLicenceType" from="drivingLicence.type"/>
			</default-value-calculator>
		</property>
									
		<method name="translate">		
			<calculator class="org.openxava.test.calculators.TranslateCarrierNameCalculator"/>
		</method>						
		
		<method name="translateToEnglish">		
			<calculator class="org.openxava.test.calculators.TranslateCarrierNameCalculator">
				<set property="targetLanguage" value="EN"/>
			</calculator>
		</method>						
		
		<method name="translateToSpanish">		
			<calculator class="org.openxava.test.calculators.TranslateCarrierNameCalculator">
				<set property="targetLanguage" value="ES"/>
			</calculator>
		</method>						
								
		<finder name="all" arguments="" collection="true"/>
						
	</entity>
	
	<view>
		<property-view property="calculated">
			<action action="Carriers.translateName"/>		
		</property-view>		
		<reference-view reference="drivingLicence">
			<descriptions-list/>
		</reference-view>
		
		<collection-view collection="fellowCarriers" view="Simple" edit-only="true">
			<list-action action="Carriers.translateName"/>
			<list-action action="Carriers.allToEnglish"/> 
		</collection-view>		
		
		<collection-view collection="fellowCarriersCalculated" view="Simple">		
			<list-action action="Carriers.translateName"/>
		</collection-view>
		
	</view>
	
	<view name="Simple">
		<members>number, name</members>
	</view>
	
	<tab>
		<properties>calculated, number, name</properties>
	</tab>
				
	<entity-mapping table="XAVATEST.CARRIER">
		<property-mapping
			property="number" column="NUMBER"  cmp-type="Integer">
			<converter class="org.openxava.converters.IntegerNumberConverter"/>			
		</property-mapping>
		<property-mapping
			property="name" column="NAME"/>
		<reference-mapping reference="drivingLicence">
			<!-- Not in the same order that in DrivingLicence, to test that OpenXava order they -->
			<reference-mapping-detail 
				column="DRIVINGLICENCE_LEVEL" 
				referenced-model-property="level"/> 																
			<reference-mapping-detail 
				column="DRIVINGLICENCE_TYPE" 
				referenced-model-property="type">
				<converter class="org.openxava.converters.NotNullStringConverter"/>
			</reference-mapping-detail>	
		</reference-mapping>				
		<reference-mapping reference="warehouse">
			<reference-mapping-detail 
				column="WAREHOUSE_ZONE" 
				referenced-model-property="zoneNumber"/> 
			<reference-mapping-detail 
				column="WAREHOUSE_NUMBER" 
				referenced-model-property="number"/> 				
		</reference-mapping>	
		<property-mapping property="remarks" column="REMARKS"/>
	</entity-mapping> 
				
</component>

=== GabrielNicolasAvellaneda/OpenXava/trunk/OpenXavaTest/components/Warehouse.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE component SYSTEM "dtds/component.dtd">

<component name="Warehouse">

	<entity>
		<property name="zoneNumber" key="true"
			size="3" required="true" type="int"/>   			
		<property name="number" key="true"
			size="3" required="true" type="int"/>   
		<property name="name" type="String"
			size="40" required="true"/>
		<!-- tmp: This must be to move to a generic place -->
		<postcreate-calculator class="org.openxava.tracking.AccessTrackingCalculator">
			<set property="accessType" value="Create"/>
		</postcreate-calculator>
		<postload-calculator class="org.openxava.tracking.AccessTrackingCalculator">
			<set property="accessType" value="Read"/>
		</postload-calculator>		
		<postmodify-calculator class="org.openxava.tracking.AccessTrackingCalculator">
			<set property="accessType" value="Update"/>
		</postmodify-calculator>
		<preremove-calculator class="org.openxava.tracking.AccessTrackingCalculator">
			<set property="accessType" value="Delete"/>
		</preremove-calculator>		
	</entity>
			
	<tab>
		<filter class="org.openxava.test.filters.LimitZoneFilter"/>
		<base-condition>${zoneNumber} &lt;= ?</base-condition>
	</tab>		
								
	<entity-mapping table="XAVATEST@separator@WAREHOUSE">
		<property-mapping 
			property="zoneNumber" column="ZONE"/>	
		<property-mapping 
			property="number" column="NUMBER"  cmp-type="Integer">
			<converter class="org.openxava.converters.IntegerNumberConverter"/>						
		</property-mapping>
		<property-mapping
			property="name" column="NAME"/>
	</entity-mapping> 
	
</component>

=== GabrielNicolasAvellaneda/OpenXava/OpenXavaTest/components/CustomerContactPerson.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE component SYSTEM "dtds/component.dtd">

<!-- 
This is only for testing a single reference as key, 
but remember this is not an example of good OO modeling.
 -->

<component name="CustomerContactPerson">

	<entity>
		<reference name="customer" key="true"/>
		<property name="name" stereotype="PERSON_NAME" required="true"/>	
	</entity>

	<view>
		<reference-view reference="customer" view="Simple"/>
	</view>
			
	<entity-mapping table="XAVATEST@separator@CUSTOMERCONTACTPERSON">
		<reference-mapping reference="customer">
			<reference-mapping-detail 
				column="CUSTOMER_NUMBER" 				
				referenced-model-property="number"/> 
		</reference-mapping>			
		<property-mapping
			property="name" column="NAME"/>
	</entity-mapping> 	
							
</component>

=== GabrielNicolasAvellaneda/OpenXava/trunk/OpenXavaTest/filtered-files/Shipment.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE component SYSTEM "dtds/component.dtd">

<!--
	Example of valid-values with converter used as key
-->

<component name="Shipment">

	<entity>  
		<property name="type" key="true" required="true">
			<valid-values>
				<valid-value value="internal"/>
				<valid-value value="external"/>
			</valid-values>
		</property>
		<property name="mode" key="true" required="true">
			<valid-values>
				<valid-value value="slow"/>
				<valid-value value="medium"/>
				<valid-value value="fast"/>
			</valid-values>
		</property>		
		<property name="number" type="int" key="true" size="5" required="true"/>
		<property name="description" type="String" size="50" required="true"/>
		<property name="time" type="java.sql.Timestamp"/>
		<reference name="customerContactPerson"/>
		<finder name="byMode" arguments="int mode" collection="true">
			<condition>${mode} = {0}</condition>
		</finder>
		<finder name="all" arguments="" collection="true"/>
	</entity>		
	
	<view>
		<reference-view reference="customerContactPerson" view="Simple"/>
	</view>
	
	<tab>
		<properties>number, description, time</properties>
	</tab>
	
	<entity-mapping table="XAVATEST_SHIPMENT">
		<property-mapping
			property="type" column="TYPE" cmp-type="String">
			<converter class="org.openxava.converters.ValidValuesLetterConverter">
				<set property="letters" value="IE"/>
			</converter>
		</property-mapping>
		<property-mapping
			property="mode" column="MODE"/>		
		<property-mapping
			property="number" column="NUMBER"/>
		<property-mapping
			property="description" column="DESCRIPTION"/>			
		<property-mapping
			property="time" column="TIME"/>						
		<reference-mapping reference="customerContactPerson">
			<reference-mapping-detail 
				column="CUSTOMERCONTACT" 
				referenced-model-property="customer.number"/>
		</reference-mapping>
	</entity-mapping>
	
</component>

=== GabrielNicolasAvellaneda/OpenXava/trunk/OpenXavaTest/filtered-files/Ingredient.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE component SYSTEM "dtds/component.dtd">

<component name="Ingredient">

	<entity>
		<property name="oid" type="String" key="true" hidden="true">
			<default-value-calculator class="org.openxava.calculators.UUIDCalculator"/>
		</property>
		<property name="name" type="String"
			size="40" required="true"/>			  			
		<reference name="partOf" model="Ingredient"/>
	</entity>
	
	<view>
		<reference-view reference="partOf">
			<descriptions-list/>
		</reference-view>
	</view>
		
	<entity-mapping table="XAVATEST_INGREDIENT">
		<property-mapping
			property="oid" column="ID"/>
		<property-mapping
			property="name" column="NAME"/>
		<reference-mapping reference="partOf">
			<reference-mapping-detail column="PARTOF" referenced-model-property="oid"/>
		</reference-mapping>	
	</entity-mapping> 
						
</component>

=== GabrielNicolasAvellaneda/OpenXava/OpenXavaTest/web/WEB-INF/classes/Formula.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE component SYSTEM "dtds/component.dtd">

<component name="Formula">

	<entity>
		<property name="oid" type="String" key="true" hidden="true">
			<default-value-calculator class="org.openxava.calculators.UUIDCalculator" on-create="true"/>
		</property>
		<property name="name" type="String"
			size="40" required="true"/>			  			
		<collection name="ingredients">
			<reference model="FormulaIngredient"/>
		</collection>	
		<property name="recipe" stereotype="HTML_TEXT"/>
		<finder name="byName" arguments="String name">
			<condition>${name} = {0}</condition>
		</finder>
	</entity>
	
	<aggregate name="FormulaIngredient">
		<property name="oid" type="String" key="true" hidden="true">
			<default-value-calculator class="org.openxava.calculators.UUIDCalculator"/>
		</property>
		
		<reference name="ingredient" model="Ingredient"/>
		<reference name="accentuate" model="Ingredient"/>
		<reference name="anotherFormula" model="Formula"/>
	</aggregate>
	
	<view>
		<members>
			name;
			<section name="ingredients">
				ingredients
			</section>
			<section name="recipe">
				recipe
			</section>
			
		</members>		
	</view>
	

	<view model="FormulaIngredient">

		<reference-view reference="ingredient">
			<descriptions-list/>
		</reference-view>

		<reference-view reference="accentuate" >
			<descriptions-list condition="${partOf.oid} = ?" depends="this.ingredient"/>
		</reference-view>		
		
		<reference-view reference="anotherFormula">
			<descriptions-list/>
		</reference-view>		
		
	</view>

	<view name="Simple" members="name"/> 
							
	<entity-mapping table="XAVATEST.FORMULA">
		<property-mapping
			property="oid" column="ID"/>
		<property-mapping
			property="name" column="NAME"/>
		<property-mapping
			property="recipe" column="RECIPE"/>
	</entity-mapping> 
	
	<aggregate-mapping aggregate="FormulaIngredient" table="XAVATEST.FORMULAINGREDIENT">
		<property-mapping
			property="oid" column="ID"/>
		<reference-mapping reference="formula">
			<reference-mapping-detail column="FORMULA" referenced-model-property="oid"/>
		</reference-mapping>	
		<reference-mapping reference="ingredient">
			<reference-mapping-detail column="INGREDIENT" referenced-model-property="oid"/>
		</reference-mapping>	
		<reference-mapping reference="accentuate">
			<reference-mapping-detail column="ACCENTUATE" referenced-model-property="oid"/>
		</reference-mapping>			
		<reference-mapping reference="anotherFormula">
			<reference-mapping-detail column="ANOTHERFORMULA" referenced-model-property="oid"/>
		</reference-mapping>			
	</aggregate-mapping> 
					
</component>

=== GabrielNicolasAvellaneda/OpenXava/OpenXavaTest/components/Worker.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE component SYSTEM "dtds/component.dtd">

<!-- 
This component is mapping to an unqualified table,
ISSUE, without schema, this is for testing the
default schema behaviour
 -->

<component name="Worker">

	<entity>
		<property name="id" type="Integer" key="true" hidden="true"/>
		<property name="nickName" type="String" 
			size="40" required="true"/>		
		<property name="fullName" type="String" 
			size="40" required="true"/>
	</entity>
	
	<entity-mapping table="ISSUE">
		<property-mapping
			property="id" column="ID"/>
		<property-mapping
			property="nickName" column="NICKNAME"/>
		<property-mapping
			property="fullName" column="FULLNAME"/>			
	</entity-mapping>
					
</component>
