=== GabrielNicolasAvellaneda/OpenXava/MySchool/xava/dtds/default-size.dtd
<!ELEMENT default-size (for-stereotype|for-type)+>

<!ELEMENT for-stereotype EMPTY>
<!ATTLIST for-stereotype
 name CDATA #REQUIRED
 size CDATA #REQUIRED
>

<!ELEMENT for-type EMPTY>
<!ATTLIST for-type
 class CDATA #REQUIRED
 size CDATA #REQUIRED
>

=== GabrielNicolasAvellaneda/OpenXava/OpenXava/xava/default-size.xml
<?xml version = "1.0" encoding = "ISO-8859-1"?>

<!DOCTYPE default-size SYSTEM "dtds/default-size.dtd">

<default-size>

	<for-stereotype name="DINERO" size="15" scale="2"/>
	<for-stereotype name="MONEY" size="15" scale="2"/>
	<for-stereotype name="TEXTO_GRANDE" size="500"/>
	<for-stereotype name="MEMO" size="500"/>
	<for-stereotype name="TEXT_AREA" size="500"/>
	<for-stereotype name="HTML_TEXT" size="3000"/>
	<for-stereotype name="TEXTO_HTML" size="3000"/>
	<for-stereotype name="HORA" size="5"/>	
	<for-stereotype name="TIME" size="5"/>  
	<for-type class="java.sql.Time" size="5"/>
	<for-type class="java.util.Date" size="10"/>
	<for-type class="java.sql.Timestamp" size="10"/>
	<for-type class="java.lang.String"  size="50"/>
	<for-type class="boolean"  size="1"/>
	<for-type class="int"  size="9"/>
	<for-type class="long"  size="15"/>
	<for-type class="java.math.BigDecimal" size="15" scale="2"/>
</default-size>
