=== GabrielNicolasAvellaneda/OpenXava/MiEscuela/xavax/dtds/editors.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT editors (editor*)>


<!ELEMENT editor (property*, formatter?, (for-type | for-stereotype | for-model-property)+)>
<!ATTLIST editor
 clasa CDATA #IMPLIED
 url CDATA #IMPLIED
 format (true|false) "true" 
 depends-stereotypes CDATA #IMPLIED
 depends-properties CDATA #IMPLIED
 frame (true|false) "false" 
>

<!ELEMENT property EMPTY>
<!ATTLIST property
  name CDATA #REQUIRED
  value CDATA #REQUIRED
>

<!ELEMENT formatter EMPTY>
<!ATTLIST formatter
  class CDATA #REQUIRED
>


<!ELEMENT for-type EMPTY>
<!ATTLIST for-type
 type CDATA #REQUIRED
>

<!ELEMENT for-stereotype EMPTY>
<!ATTLIST for-stereotype
 stereotype CDATA #REQUIRED
>

<!ELEMENT for-model-property EMPTY>
<!ATTLIST for-model-property
 model CDATA #REQUIRED
 property CDATA #REQUIRED 
>

=== GabrielNicolasAvellaneda/OpenXava/Addons/xava/editors.xml
<?xml version = "1.0" encoding = "ISO-8859-1"?>

<!DOCTYPE editors SYSTEM "dtds/editors.dtd">

<!-- NaviOX -->

<editors>
	
	<editor url="textEditor.jsp">
		<for-model-property model="User" property="name" />		
		<for-model-property model="SignIn" property="user" />				
		<for-model-property model="Role" property="name" />
		<for-model-property model="Module" property="name" />		
		<for-model-property model="Module" property="application" />						
	</editor>
	
	<editor url="../../naviox/editors/actionsEditor.jsp" frame="true">			
		<formatter class="com.openxava.naviox.formatters.ArrayAsStringFormatter" />	
		<list-formatter class="com.openxava.naviox.formatters.ActionsListFormatter" />
		<for-model-property model="ModuleRights" property="excludedActions" />
	</editor>

	<editor url="../../naviox/editors/organizationUrlEditor.jsp">
		<for-model-property model="Organization" property="url" />
	</editor>	
	
</editors>

=== GabrielNicolasAvellaneda/OpenXava/trunk/OpenXava/xava/default-editors.xml
<?xml version = "1.0" encoding = "ISO-8859-1"?>

<!DOCTYPE editors SYSTEM "dtds/editors.dtd">

<!--
	In your project use the name 'editors.xml' or 'editores.xml'
-->

<editors>

	<editor name="TextField" url="textEditor.jsp">
		<for-type type="java.lang.String" />
		<for-type type="java.math.BigDecimal" />
		<for-type type="java.math.BigInteger" />
		<for-type type="int" />
		<for-type type="java.lang.Integer" />
		<for-type type="long" />
		<for-type type="java.lang.Long" />
	</editor>

	<editor name="BooleanCheckBox" url="booleanEditor.jsp">
		<formatter class="org.openxava.formatters.BooleanFormatter" />		<for-type type="boolean" />		<for-type type="java.lang.Boolean" />	</editor>	<editor name="DateCalendar" url="dateCalendarEditor.jsp">
		<formatter class="org.openxava.formatters.DateFormatter" />		<for-type type="java.util.Date" />	</editor>

	<editor name="ValidValuesCombo" url="validValuesEditor.jsp">
		<for-valid-values />
	</editor>

	<editor name="ValidValuesRadioButton" url="radioButtonEditor.jsp">
		<property name="horizontal" value="true" />
	</editor>
	<editor name="ValidValuesVerticalRadioButton"
		url="radioButtonEditor.jsp">
		<property name="horizontal" value="true" />
	</editor>
	<editor name="ValidValuesHorizontalRadioButton"
		url="radioButtonEditor.jsp">
		<property name="horizontal" value="true" />
	</editor>

	<editor name="Enum" url="validValuesEditor.jsp">
		<for-type type="java.lang.Enum" />
	</editor>

	<editor name="StringTime" url="textEditor.jsp">
		<formatter class="org.openxava.formatters.StringTimeFormatter" />
		<for-stereotype stereotype="HORA" />
		<for-stereotype stereotype="TIME" />
	</editor>

	<editor name="Timestamp" url="textEditor.jsp">
		<formatter class="org.openxava.formatters.SQLTimeFormatter" />
		<for-type type="java.sql.Time" />
	</editor>

	<editor name="Money" url="moneyEditor.jsp">
		<formatter class="org.openxava.formatters.MoneyFormatter" />
		<for-stereotype stereotype="DINERO" />
		<for-stereotype stereotype="MONEY" />
	</editor>
	
	<editor name="Email" url="textEditor.jsp">
        <for-stereotype stereotype="EMAIL"/>
    </editor>
    
    <editor name="WebURL" url="textEditor.jsp">
        <for-stereotype stereotype="WEBURL"/>
    </editor>
    
	<editor name="Image" url="imageEditor.jsp" format="false">
		<formatter class="org.openxava.formatters.ImageFormatter" />
		<for-stereotype stereotype="FOTO" />
		<for-stereotype stereotype="PHOTO" />
		<for-stereotype stereotype="IMAGEN" />
		<for-stereotype stereotype="IMAGE" />
	</editor>

	<editor name="TextArea" url="textAreaEditor.jsp" frame="true">
		<for-stereotype stereotype="TEXTO_GRANDE" />
		<for-stereotype stereotype="MEMO" />
		<for-stereotype stereotype="TEXT_AREA" />
	</editor>

	<editor name="Label" url="labelEditor.jsp">
		<formatter from-type="true" />
		<for-stereotype stereotype="ETIQUETA" />
		<for-stereotype stereotype="LABEL" />
	</editor>

	<editor name="DateTimeCalendar" url="dateTimeCalendarEditor.jsp">
		<formatter class="org.openxava.formatters.DateTimeFormatter" />
		<for-type type="java.sql.Timestamp" />
		<for-stereotype stereotype="DATETIME" />
		<for-stereotype stereotype="FECHAHORA" />
	</editor>

	<editor name="BoldLabel" url="boldLabelEditor.jsp">
		<for-stereotype stereotype="ETIQUETA_NEGRITA" />
		<for-stereotype stereotype="BOLD_LABEL" />
	</editor>

	<editor name="Gallery" url="galleryEditor.jsp">
		<for-stereotype stereotype="IMAGES_GALLERY" />
		<for-stereotype stereotype="GALERIA_IMAGENES" />
	</editor>

	<editor name="ZeroFilled" url="textEditor.jsp">
		<property name="fillWithZeros" value="true" />
		<for-stereotype stereotype="ZEROS_FILLED" />
		<for-stereotype stereotype="RELLENADO_CON_CEROS" />
	</editor>

	<!-- 
		This steroetype is not for be assigned directly to a property, 
		but it's used internally by OpenXava to render actions inside views.
	-->
	<editor url="actionEditor.jsp">
		<for-stereotype stereotype="__ACTION__" />
	</editor>

	<editor name="HtmlText" url="htmlEditor.jsp" frame="true">
		<for-stereotype stereotype="HTML_TEXT" />
		<for-stereotype stereotype="TEXTO_HTML" />
	</editor>

	<!-- 
	It shows an image localized in /xava/images of your web applications,
	with the patter [prefix][propertyContent].[extesion].
	That is, if the property value is 'RED', it will show the image:
	/xava/images/imageLabel_RED.gif.
	You can see an example in the 'sample' property of Color component 
	in OpenXavaTest.
	-->
	<editor name="ImageLabel" url="imageLabelEditor.jsp">
		<property name="prefix" value="imageLabel_" />
		<property name="extension" value="gif" />
		<formatter from-type="true" />
		<for-stereotype stereotype="IMAGE_LABEL" />
		<for-stereotype stereotype="ETIQUETA_IMAGEN" />
	</editor>

</editors>

=== GabrielNicolasAvellaneda/OpenXava/OpenXava/xava/default-editors.xml
<?xml version = "1.0" encoding = "ISO-8859-1"?>

<!DOCTYPE editors SYSTEM "dtds/editors.dtd">

<!--
In your project use the name 'editors.xml' or 'editores.xml'
-->

<editors>

  <editor url="textEditor.jsp"> 
    <for-type type="java.lang.String"/>
    <for-type type="java.math.BigDecimal"/>
    <for-type type="java.math.BigInteger"/>
    <for-type type="int"/>
    <for-type type="java.lang.Integer"/>    
    <for-type type="long"/>
    <for-type type="java.lang.Long"/>    
  </editor>
      <editor url="booleanEditor.jsp">
		<formatter class="org.openxava.formatters.BooleanFormatter"/>      	    <for-type type="boolean"/>    <for-type type="java.lang.Boolean"/>  </editor>        <editor url="dateCalendarEditor.jsp">
	<formatter class="org.openxava.formatters.DateFormatter"/>    <for-type type="java.util.Date"/>  </editor>    
  
  <editor url="validValuesEditor.jsp">
  	<for-valid-values/>
  </editor>
  
  <editor url="validValuesEditor.jsp">
  	<for-type type="java.lang.Enum"/>
  </editor>  
    
  <editor url="textEditor.jsp">
	<formatter class="org.openxava.formatters.StringTimeFormatter"/>
    <for-stereotype stereotype="HORA"/>
    <for-stereotype stereotype="TIME"/>		
  </editor>	
  
  <editor url="textEditor.jsp">
	<formatter class="org.openxava.formatters.SQLTimeFormatter"/>
    <for-type type="java.sql.Time"/>
  </editor>	
  
  <editor url="moneyEditor.jsp">		
    <for-stereotype stereotype="DINERO"/>
	<for-stereotype stereotype="MONEY"/>
  </editor>
    
  <editor url="imageEditor.jsp" format="false">
    <formatter class="org.openxava.formatters.ImageFormatter"/>
    <for-stereotype stereotype="FOTO"/>
	<for-stereotype stereotype="PHOTO"/>		
    <for-stereotype stereotype="IMAGEN"/>
    <for-stereotype stereotype="IMAGE"/>		
  </editor>
  
  <editor url="textAreaEditor.jsp" frame="true">
    <for-stereotype stereotype="TEXTO_GRANDE"/>
		<for-stereotype stereotype="MEMO"/>
		<for-stereotype stereotype="TEXT_AREA"/>
  </editor>
  
  <editor url="labelEditor.jsp">
		<formatter from-type="true"/>		
    <for-stereotype stereotype="ETIQUETA"/>
    <for-stereotype stereotype="LABEL"/>
  </editor>
      
  <editor url="dateTimeCalendarEditor.jsp">
	<formatter class="org.openxava.formatters.DateTimeFormatter"/>
	<for-type type="java.sql.Timestamp"/> 
    <for-stereotype stereotype="DATETIME"/>
    <for-stereotype stereotype="FECHAHORA"/>
  </editor>    
  
  <editor url="boldLabelEditor.jsp">
	<for-stereotype stereotype="ETIQUETA_NEGRITA"/>
    <for-stereotype stereotype="BOLD_LABEL"/>
  </editor>
  
  <editor url="galleryEditor.jsp">
	<for-stereotype stereotype="IMAGES_GALLERY"/>
	<for-stereotype stereotype="GALERIA_IMAGENES"/>
  </editor>
  
   <editor url="textEditor.jsp"> 
   	<property name="fillWithZeros" value="true"/>
	<for-stereotype stereotype="ZEROS_FILLED"/>
	<for-stereotype stereotype="RELLENADO_CON_CEROS"/>
  </editor>
    
  <!-- 
  This steroetype is not for be assigned directly to a property, 
  but it's used internally by OpenXava to render actions inside views.
  -->  
  <editor url="actionEditor.jsp"> 
	<for-stereotype stereotype="__ACTION__"/>
  </editor>
  
  <editor url="htmlEditor.jsp" frame="true">
    <for-stereotype stereotype="HTML_TEXT"/>
    <for-stereotype stereotype="TEXTO_HTML"/>
  </editor>
        
</editors>

=== GabrielNicolasAvellaneda/OpenXava/OpenXavaTest/xava/editors.xml
<?xml version = "1.0" encoding = "ISO-8859-1"?>

<!DOCTYPE editors SYSTEM "dtds/editors.dtd">

<!-- OpenXavaTest -->

<editors>

  <!-- For work only in uppercase -->	
  <editor url="textEditor.jsp"> 
		<formatter class="org.openxava.formatters.UpperCaseFormatter"/>
    <for-type type="java.lang.String"/>
  </editor>
	
  <editor url="textEditor.jsp"> 
    <for-stereotype stereotype="NO_FORMATING_STRING"/>
  </editor>

  <editor url="textEditor.jsp">
		<formatter class="org.openxava.test.formatters.PersonNameFormatter"> 
			<set property="firstLetterInUpperCase" value="true"/>	
		</formatter>
    <for-stereotype stereotype="PERSON_NAME"/>
  </editor>
	      
  <editor url="textEditor.jsp">
    <for-model-property model="Product" property="unitPrice"/>
  </editor>
      
  <editor url="descriptionsEditor.jsp">
		<property name="model" value="Family"/>
		<property name="keyProperty" value="number"/>
		<property name="descriptionProperty" value="description"/>
		<property name="orderByKey" value="true"/>
		<property name="readOnlyAsLabel" value="true"/>
    <for-stereotype stereotype="FAMILY"/>
  </editor>
      
  <!-- It is possible to specify dependencies from stereotypes or properties -->    
  <editor url="descriptionsEditor.jsp" depends-stereotypes="FAMILY">          
  <!--  
  <editor url="descriptionsEditor.jsp" depends-properties="familyNumber">
  -->	
		<property name="model" value="Subfamily"/>
		<property name="keyProperty" value="number"/>
		<property name="descriptionProperties" value="number, description"/>
		<property name="condition" value="${familyNumber} = ?"/>
		<property name="parameterValuesStereotypes" value="FAMILY"/>	
		<!--
		<property name="parameterValuesProperties" value="familyNumber"/>
		-->		
		<property name="descriptionsFormatter" value="org.openxava.test.formatters.FamilyDescriptionsFormatter"/>	
		<for-stereotype stereotype="SUBFAMILY"/>
  </editor>

  <editor url="descriptionsEditor.jsp" depends-properties="family.number"> 
		<property name="model" value="Subfamily"/>
		<property name="keyProperty" value="number"/>
		<property name="descriptionProperties" value="description"/>
		<property name="condition" value="${familyNumber} = ?"/>
		<property name="parameterValuesProperties" value="family.number"/>
		<for-stereotype stereotype="SUBFAMILY_DEPENDS_REFERENCE"/>
  </editor>
  
  <editor	url="descriptionsEditor.jsp" frame="true">
  	<property name="model" value="Warehouse"/>
  	<property name="keyProperties" value="zoneNumber, number"/>
		<property name="descriptionProperty" value="name"/>
		<property name="filter" value="org.openxava.test.filters.DefaultZoneFilter"/>
		<property name="condition" value="${zoneNumber} = ?"/>
  	<formatter class="org.openxava.test.formatters.WarehouseKeyFormatter"/>	
    <for-stereotype stereotype="WAREHOUSE"/>
  </editor>
	
  <editor url="descriptionsEditor.jsp" depends-properties="family, detail.subfamily">
  	<property name="model" value="ServiceType"/>
  	<property name="keyProperty" value="number"/>
		<property name="descriptionProperty" value="description"/>
		<property name="condition" value="${family} = ? and ${subfamily} = ?"/>
		<property name="parameterValuesProperties" value="family, detail.subfamily"/>
    <for-stereotype stereotype="SERVICE_TYPE"/>
  </editor>
	
  <editor url="descriptionsEditor.jsp" depends-properties="oid">
  	<property name="model" value="Product3"/>
  	<property name="keyProperty" value="number"/>
		<property name="descriptionProperty" value="description"/>
		<property name="condition" value="${family.oid} = ?"/>
		<property name="parameterValuesProperties" value="oid"/>
    <for-stereotype stereotype="PRODUCT3"/>
  </editor>
	
  <editor url="descriptionsEditor.jsp">
  	<property name="model" value="Customer.Receptionist"/>
  	<property name="keyProperty" value="oid"/>
		<property name="descriptionProperty" value="name"/>
    <for-stereotype stereotype="RECEPTIONIST"/>
  </editor>
	        
</editors>
